# Generated by Django 5.0.3 on 2025-01-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupManagement',
        ),
        migrations.AlterModelOptions(
            name='backuprecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Database Backup', 'verbose_name_plural': 'Database Backups'},
        ),
    ]
