# Generated by Django 5.0.3 on 2025-01-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0002_delete_backupmanagement_alter_backuprecord_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Backup Management',
                'verbose_name_plural': 'Backup Management',
            },
        ),
        migrations.DeleteModel(
            name='BackupRecord',
        ),
    ]
