version: '3.9'

services:
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    networks:
      - web_network
    dns:
      - 8.8.8.8

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    networks:
      - web_network
      - db_network
    dns:
      - 8.8.8.8

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
    env_file:
      - .env.prod.db
    networks:
      - db_network
    dns:
      - 8.8.8.8

  redis:
    image: redis:7.0.10-alpine
    ports:
      - 6379:6379
    networks:
      - db_network
    dns:
      - 8.8.8.8

  celery:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A django_project worker --loglevel=info
    env_file:
      - .env.prod
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    networks:
      - db_network
    dns:
      - 8.8.8.8

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
  static_volume:
  media_volume:

networks:
  web_network:
  db_network:
