# Dockerfile.webpack

FROM node:18-alpine

WORKDIR /code

COPY package.json package-lock.json /code/

RUN npm install

COPY webpack.config.js ./
COPY tailwind.config.js ./
COPY postcss.config.js ./

# Copy the static assets explicitly
COPY ./static ./static

COPY . /code/


