# Dockerfile.webpack
FROM node:18-alpine

WORKDIR /code

# Copy package files
COPY package.json package-lock.json ./

# Install local dependencies
RUN npm install

# Copy configuration files
COPY webpack.config.js ./
COPY tailwind.config.js ./
COPY postcss.config.js ./

# Copy the static assets
COPY ./static ./static

# Copy remaining files
COPY . /code/
