version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  redis:
    image: redis:7.0.10-alpine
    ports:
      - 6379:6379

  celery:
    build: .
    command: celery -A django_project worker --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
