version: '3.9'

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile.prod
    expose:
      - 8000
    volumes:
      # - static_volume:/code/static
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    env_file:
      - .env.prod
    depends_on:
      - db
    

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
 

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:

  postgres_data:
  Caddyfile:
  caddy_data:
  caddy_config:
  static_volume:
  media_volume:

