version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:${DJANGO_PORT}
    volumes:
      - .:/code
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    env_file:
      - .env
    depends_on:
      - db


  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5433:5433"
    command: -p 5433

  redis:
    image: redis:7.0.10-alpine
    ports:
      - 6379:6379

  celery:
    build: .
    command: celery -A django_project worker --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
