version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.django
    command: python manage.py runserver 0.0.0.0:${DJANGO_PORT}
    volumes:
      - .:/code
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    env_file:
      - .env
    depends_on:
      - db

  webpack:
    build:
      context: .
      dockerfile: Dockerfile.webpack  # Create a separate Dockerfile for Webpack
    command: npm run watch  # Using watch mode
    stdin_open: true        # Add for interactive inputs
    tty: true               # Keep the terminal session open
    volumes:
      - .:/code
    depends_on:
      - web
    environment:
      - NODE_ENV=development


  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5433:5433"
    command: -p 5433

  redis:
    image: redis:7.0.10-alpine
    ports:
      - 6379:6379

  celery:
    build: .
    command: celery -A django_project worker --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
