version: '3.9'

services:
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:${DJANGO_PORT}
    volumes:
      - .:/code
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    env_file:
      - .env
    depends_on:
      - db

  webpack:
    build:
      context: .
      dockerfile: Dockerfile.webpack
    command: sh -c "npm install && FORCE_COLOR=1 npm run watch"
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    depends_on:
      - web
    environment:
      - NODE_ENV=development
      - FORCE_COLOR=1


  db:
    image: postgres:13-alpine
    volumes:
      - postgres_djangox:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    ports:
      - "${SQL_PORT}:5433"
    command: -p 5433
    env_file:
      - .env

volumes:
  postgres_djangox:
