services:
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    networks:
      - web_network

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
    networks:
      - web_network
      - db_network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
    networks:
      - db_network

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  web_network:
  db_network: