# Generated by Django 5.0.3 on 2024-07-21 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='approval',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='approval',
            name='is_approved',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('document', 'step', 'approver')},
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('workflow', 'order')},
        ),
    ]
