# Generated by Django 5.0.3 on 2024-07-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_remove_document_is_approved_approval_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together=set(),
        ),
    ]
