# Generated by Django 5.0.3 on 2024-07-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_approval_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='recorded_at',
            field=models.DateTimeField(null=True),
        ),
    ]
