# Generated by Django 5.0.3 on 2024-07-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_approval_recorded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='condition_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='condition_operator',
            field=models.CharField(blank=True, choices=[('gt', 'Greater Than'), ('lt', 'Less Than'), ('eq', 'Equal To'), ('in', 'In List')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='condition_value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
