# Generated by Django 5.0.3 on 2024-07-26 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_approvalstep_condition_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalstep',
            name='condition_field',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='condition_operator',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='condition_value',
        ),
    ]
