# Generated by Django 5.0.3 on 2024-07-26 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_remove_approvalstep_condition_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
