# Generated by Django 5.0.3 on 2024-07-26 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_document_last_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dynamic_field_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Yes/No'), ('choice', 'Multiple Choice')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('choices', models.TextField(blank=True, help_text="Comma-separated choices for 'choice' field type")),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_fields', to='document.approvalworkflow')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
