# Generated by Django 5.0.3 on 2024-07-26 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_document_dynamic_field_values_dynamicfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_values', to='document.document')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.dynamicfield')),
            ],
            options={
                'unique_together': {('document', 'field')},
            },
        ),
    ]
