# Generated by Django 5.0.3 on 2024-07-27 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_dynamicfieldvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='dynamic_field_values',
        ),
    ]
