# Generated by Django 5.0.3 on 2024-07-27 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_remove_document_dynamic_field_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='approvers',
            field=models.ManyToManyField(blank=True, null=True, related_name='approval_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='condition_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.dynamicfield'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='condition_operator',
            field=models.CharField(blank=True, choices=[('eq', 'Equals'), ('ne', 'Not Equals'), ('gt', 'Greater Than'), ('lt', 'Less Than'), ('gte', 'Greater Than or Equal'), ('lte', 'Less Than or Equal')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='condition_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='is_conditional',
            field=models.BooleanField(default=False),
        ),
    ]
