# Generated by Django 5.0.3 on 2024-07-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_approvalstep_approvers_approvalstep_condition_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalworkflow',
            name='allow_custom_approvers',
            field=models.BooleanField(default=False),
        ),
    ]
