# Generated by Django 5.0.3 on 2024-07-27 09:37

import document.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_approvalworkflow_allow_custom_approvers'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=document.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='approval',
            name='user_input',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='allowed_file_extensions',
            field=models.CharField(blank=True, help_text="Comma-separated file extensions for 'file' input type", max_length=255),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='input_choices',
            field=models.TextField(blank=True, help_text="Comma-separated choices for 'choice' input type"),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='input_prompt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='input_type',
            field=models.CharField(choices=[('none', 'No Input Required'), ('text', 'Text Input'), ('number', 'Number Input'), ('date', 'Date Input'), ('choice', 'Multiple Choice'), ('file', 'File Upload')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='requires_input',
            field=models.BooleanField(default=False),
        ),
    ]
