# Generated by Django 5.0.3 on 2024-07-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_approval_uploaded_file_approval_user_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='email_body_template',
            field=models.TextField(blank=True, help_text='Use {document}, {approver}, and {step} as placeholders'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='email_subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
