# Generated by Django 5.0.3 on 2024-07-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_approvalstep_email_body_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='cc_emails',
            field=models.TextField(blank=True, help_text='Comma-separated email addresses for CC'),
        ),
    ]
