# Generated by Django 5.0.3 on 2024-07-28 00:54

import document.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0017_approvalworkflow_send_reject_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfieldvalue',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=document.models.dynamic_field_file_path),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='input_type',
            field=models.CharField(choices=[('none', 'No Input Required'), ('text', 'Text Input'), ('number', 'Number Input'), ('date', 'Date Input'), ('choice', 'Multiple Choice'), ('file', 'File Upload'), ('attachment', 'File Attachment')], default='none', max_length=10),
        ),
    ]
