# Generated by Django 5.0.3 on 2024-07-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0018_dynamicfieldvalue_file_alter_approvalstep_input_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='allowed_extensions',
            field=models.CharField(blank=True, help_text='Comma-separated list of allowed file extensions (e.g., .pdf,.doc,.jpg)', max_length=255),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='max_file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum file size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='multiple_files',
            field=models.BooleanField(default=False, help_text='Allow multiple file uploads for this field'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='input_type',
            field=models.CharField(choices=[('none', 'No Input Required'), ('text', 'Text Input'), ('number', 'Number Input'), ('date', 'Date Input'), ('choice', 'Multiple Choice'), ('file', 'File Upload')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='dynamicfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Yes/No'), ('choice', 'Multiple Choice'), ('attachment', 'File Attachment')], max_length=20),
        ),
    ]
