# Generated by Django 5.0.3 on 2024-07-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0020_approvalstep_email_approved_body_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalstep',
            name='email_approved_body_template',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='email_approved_subject',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='send_approved_email',
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='email_approved_body_template',
            field=models.TextField(blank=True, help_text='Use {document}, {approver}, and {step} as placeholders'),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='email_approved_subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='send_approved_email',
            field=models.BooleanField(default=False),
        ),
    ]
