# Generated by Django 5.0.3 on 2024-07-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0022_pdftemplate_reportconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Yes/No'), ('choice', 'Multiple Choice'), ('attachment', 'File Attachment'), ('product_list', 'Product List')], max_length=20),
        ),
    ]
