# Generated by Django 5.0.3 on 2024-07-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0023_alter_dynamicfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfieldvalue',
            name='json_value',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
