# Generated by Django 5.0.3 on 2024-08-04 07:28

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0024_dynamicfieldvalue_json_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('cancel', 'Cancel'), ('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='company_logo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/code/media')), upload_to='report_logos/'),
        ),
    ]
