# Generated by Django 5.0.3 on 2024-08-06 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0025_alter_document_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
