# Generated by Django 5.0.3 on 2024-08-09 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0027_remove_document_favorites_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='approval',
            constraint=models.UniqueConstraint(condition=models.Q(('is_approved__isnull', True)), fields=('document', 'step', 'approver'), name='unique_pending_approval'),
        ),
    ]
