# Generated by Django 5.0.3 on 2024-08-27 14:26

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0028_approval_unique_pending_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalstep',
            name='approvers',
            field=models.ManyToManyField(blank=True, related_name='approval_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dynamicfield',
            name='max_file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum file size in MB', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
