# Generated by Django 5.0.3 on 2024-08-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0029_alter_approvalstep_approvers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='editable_fields',
            field=models.ManyToManyField(blank=True, related_name='approval_steps', to='document.dynamicfield'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='requires_edit',
            field=models.BooleanField(default=False),
        ),
    ]
