# Generated by Django 5.0.3 on 2024-08-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0030_approvalstep_editable_fields_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalstep',
            options={'ordering': ['workflow', 'order']},
        ),
    ]
