# Generated by Django 5.0.3 on 2024-08-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0032_alter_approvalstep_editable_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalstep',
            name='editable_fields',
            field=models.ManyToManyField(blank=True, related_name='approval_steps', to='document.dynamicfield'),
        ),
    ]
