# Generated by Django 5.0.3 on 2024-08-31 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0033_alter_approvalstep_editable_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='textarea_rows',
            field=models.PositiveIntegerField(default=4, help_text='Number of rows for textarea fields', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='dynamicfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Yes/No'), ('choice', 'Multiple Choice'), ('attachment', 'File Attachment'), ('product_list', 'Product List')], max_length=20),
        ),
    ]
