# Generated by Django 5.0.3 on 2024-08-31 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0034_dynamicfield_textarea_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='input_width',
            field=models.CharField(choices=[('half', 'Half Width'), ('full', 'Full Width')], default='half', help_text='Width of the input field', max_length=4),
        ),
    ]
