# Generated by Django 5.0.3 on 2024-08-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0035_dynamicfield_input_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfield',
            name='input_width',
            field=models.CharField(choices=[('half', 'Half Width'), ('full', 'Full Width')], default='full', help_text='Width of the input field', max_length=4),
        ),
    ]
