# Generated by Django 5.0.3 on 2024-08-31 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0036_alter_dynamicfield_input_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalstep',
            name='requires_input',
        ),
    ]
