# Generated by Django 5.0.3 on 2024-08-31 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0037_remove_approvalstep_requires_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalstep',
            name='input_prompt',
        ),
    ]
