# Generated by Django 5.0.3 on 2024-08-31 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0038_remove_approvalstep_input_prompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='approval',
            name='unique_pending_approval',
        ),
        migrations.AddConstraint(
            model_name='approval',
            constraint=models.UniqueConstraint(condition=models.Q(('is_approved__isnull', True)), fields=('document', 'step', 'approver'), name='unique_active_approval'),
        ),
    ]
