# Generated by Django 5.0.3 on 2024-08-31 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0039_remove_approval_unique_pending_approval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='approval',
            name='unique_active_approval',
        ),
        migrations.AddConstraint(
            model_name='approval',
            constraint=models.UniqueConstraint(condition=models.Q(('is_approved__isnull', True)), fields=('document', 'step', 'approver'), name='unique_pending_approval'),
        ),
    ]
