# Generated by Django 5.0.3 on 2024-08-31 11:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0041_remove_approval_unique_pending_approval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('document', 'step', 'approver', 'is_approved')},
        ),
    ]
