# Generated by Django 5.0.3 on 2024-08-31 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0042_alter_approval_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together=set(),
        ),
    ]
