# Generated by Django 5.0.3 on 2024-10-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0046_alter_dynamicfield_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalworkflow',
            name='allow_custom_approvers',
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='allow_custom_approver',
            field=models.BooleanField(default=False),
        ),
    ]
