# Generated by Django 5.0.3 on 2024-10-06 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('document', '0047_remove_approvalworkflow_allow_custom_approvers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='approver_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
