# Generated by Django 5.0.3 on 2024-10-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0048_approvalstep_approver_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('last_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='document_reference',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
