# Generated by Django 5.0.3 on 2024-10-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0050_alter_document_document_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_reference',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
