# Generated by Django 5.0.3 on 2025-01-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0052_alter_document_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalworkflow',
            name='content_editor',
            field=models.BooleanField(default=True, help_text='Add content editor for document'),
        ),
    ]
