# Generated by Django 5.0.3 on 2025-01-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0053_approvalworkflow_content_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalworkflow',
            name='content_editor',
            field=models.BooleanField(default=False, help_text='Add content editor for document'),
        ),
    ]
