# Generated by Django 5.0.3 on 2025-01-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0054_alter_approvalworkflow_content_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='move_to_next',
            field=models.BooleanField(default=True, help_text='If True, move to next step. If False, complete workflow after this step.'),
        ),
    ]
