# Generated by Django 5.0.3 on 2025-01-06 17:57

import django_project.storage_backends
import document.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0056_alter_dynamicfieldvalue_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfieldvalue',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django_project.storage_backends.CustomS3Storage(), upload_to=document.models.dynamic_field_file_path),
        ),
    ]
