# Generated by Django 5.0.3 on 2025-01-09 15:44

import django.db.models.deletion
import django_project.storage_backends
import document.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0057_alter_dynamicfieldvalue_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django_project.storage_backends.CustomS3Storage(), upload_to=document.models.editor_image_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_images', to='document.document')),
            ],
        ),
    ]
