# Generated by Django 5.0.3 on 2025-01-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0058_editorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorimage',
            name='base_url',
            field=models.TextField(blank=True),
        ),
    ]
