# Generated by Django 5.0.3 on 2025-01-16 17:01

import django_project.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0059_editorimage_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfiguration',
            name='company_logo',
            field=models.ImageField(storage=django_project.storage_backends.CustomS3Storage(), upload_to='logo/'),
        ),
    ]
