# Generated by Django 4.2.9 on 2025-02-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('document', '0060_alter_reportconfiguration_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalworkflow',
            name='authorized_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups that have full access to documents in this workflow', related_name='authorized_workflows', to='auth.group'),
        ),
    ]
