# Generated by Django 4.2.9 on 2025-02-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0061_approvalworkflow_authorized_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalstep',
            name='requires_edit',
            field=models.BooleanField(default=False, help_text='Enable approvers to edit field or upload file for particular step'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='send_email',
            field=models.BooleanField(default=False, help_text='When select, approvers will be notified by email for particular step'),
        ),
        migrations.AlterField(
            model_name='approvalworkflow',
            name='send_approved_email',
            field=models.BooleanField(default=False, help_text='This email is sent to requestor when all approvers approve document'),
        ),
        migrations.AlterField(
            model_name='approvalworkflow',
            name='send_reject_email',
            field=models.BooleanField(default=True, help_text='Send email on document rejection for all steps'),
        ),
    ]
