# Generated by Django 4.2.9 on 2025-04-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0064_approvalstep_approval_mode'),
    ]

    operations = [
    ]
