# Generated by Django 4.2.9 on 2025-04-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0065_auto_20250409_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
