# Generated by Django 4.2.9 on 2025-04-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0067_dynamicfield_table_columns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfield',
            name='table_columns',
            field=models.TextField(blank=True, help_text="Pipe-separated column names for 'table_list' field type (e.g., 'item|name|qty|invoice|reason|credit')"),
        ),
    ]
