# Generated by Django 4.2.9 on 2025-04-20 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0069_approvalauthorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who actually performed the approval (may be different from approver in case of authorization)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals_performed', to=settings.AUTH_USER_MODEL),
        ),
    ]
