# Generated by Django 4.2.9 on 2025-04-20 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0070_approval_approved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='approval',
            name='on_behalf_of',
            field=models.ForeignKey(blank=True, help_text='If this approval was done on behalf of another user, this field indicates who', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegated_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
