# Generated by Django 4.2.9 on 2025-04-28 14:36

from django.db import migrations, models
import django.db.models.deletion
import django_project.storage_backends
# Define the function here instead of importing it from models
def dynamic_field_editor_image_path(instance, filename):
    return f'documents/{instance.field_value.document.document_reference}/dynamic_fields/{instance.field_value.field.id}/images/{filename}'


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0071_remove_approval_approved_by_approval_on_behalf_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalstep',
            name='email_body_template',
            field=models.TextField(blank=True, help_text='Use {document}, {approver}, {step} as placeholders. For authorized users, use {% if authorized_users %}...{% for user in authorized_users %}{{ user.full_name }}{% endfor %}...{% endif %}'),
        ),
        migrations.AlterField(
            model_name='dynamicfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Yes/No'), ('choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('attachment', 'File Attachment'), ('product_list', 'Product List'), ('table_list', 'Table List'), ('tiptap_editor', 'Rich Text Editor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='editorimage',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_images', to='document.document'),
        ),
        migrations.CreateModel(
            name='DynamicFieldEditorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django_project.storage_backends.CustomS3Storage(), upload_to=dynamic_field_editor_image_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('base_url', models.TextField(blank=True)),
                ('field_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_images', to='document.dynamicfieldvalue')),
            ],
        ),
    ]
