# Generated by Django 4.2.9 on 2025-04-28 15:21

from django.db import migrations, models
import django.db.models.deletion
import django_project.storage_backends
# Define the function here instead of importing it from models
def dynamic_field_editor_image_path(instance, filename):
    return f'documents/{instance.field_value.document.document_reference}/dynamic_fields/{instance.field_value.field.id}/images/{filename}'


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0073_remove_dynamic_field_editor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFieldEditorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django_project.storage_backends.CustomS3Storage(), upload_to=dynamic_field_editor_image_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('base_url', models.TextField(blank=True)),
                ('field_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_images', to='document.dynamicfieldvalue')),
            ],
        ),
    ]
