# Generated by Django 4.2.9 on 2025-04-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0074_dynamicfieldeditorimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DynamicFieldEditorImage',
        ),
    ]
