# Generated by Django 4.2.9 on 2025-05-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0075_delete_dynamicfieldeditorimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalstep',
            name='allowed_file_extensions',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='input_choices',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='input_type',
        ),
    ]
