# Generated by Django 4.2.9 on 2025-05-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0076_remove_approvalstep_allowed_file_extensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfield',
            name='input_width',
            field=models.CharField(choices=[('quarter', 'Quarter Width'), ('half', 'Half Width'), ('three_quarter', 'Three Quarter Width'), ('full', 'Full Width')], default='full', help_text='Width of the input field', max_length=15),
        ),
    ]
