# Generated by Django 4.2.9 on 2025-05-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0077_alter_dynamicfield_input_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalstep',
            name='cc_emails',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='email_body_template',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='email_subject',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='send_email',
        ),
    ]
