# Generated by Django 4.2.9 on 2025-05-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0078_remove_approval_step_email_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='uploaded_file',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='user_input',
        ),
        migrations.AlterField(
            model_name='approvalworkflow',
            name='send_approved_email',
            field=models.BooleanField(default=False, help_text='This email is sent to pending approver and requestor when all approvers approve document'),
        ),
    ]
