# Generated by Django 4.2.9 on 2025-05-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0079_remove_user_input_and_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='can_approveAt',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the user became eligible to approve this document', null=True),
        ),
    ]
