# Generated by Django 4.2.9 on 2025-05-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0080_approval_can_approveat'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cc_emails',
            field=models.TextField(blank=True, help_text='Comma-separated list of additional CC email addresses'),
        ),
    ]
