# Generated by Django 4.2.9 on 2025-05-17 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0081_document_cc_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='authorized_cc_users',
            field=models.ManyToManyField(blank=True, help_text='Users authorized to view this document and receive CC notifications', related_name='cc_authorized_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
