# Generated by Django 4.2.9 on 2025-05-17 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0082_document_authorized_cc_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='authorized_cc_users',
        ),
        migrations.RemoveField(
            model_name='document',
            name='cc_emails',
        ),
        migrations.AddField(
            model_name='document',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, help_text='Users authorized to view this document and receive notifications', related_name='authorized_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
