# Generated by Django 4.2.9 on 2025-05-19 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('document', '0083_remove_document_authorized_cc_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='approver_groups',
            field=models.ManyToManyField(blank=True, related_name='approval_steps', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='approver_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_approval_steps', to='auth.group'),
        ),
    ]
