# Generated by Django 4.2.9 on 2025-05-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0084_approvalstep_approver_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalstep',
            name='approver_group',
        ),
    ]
