# Generated by Django 4.2.9 on 2025-12-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0085_remove_approvalstep_approver_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='void_reason',
            field=models.TextField(blank=True, help_text='Reason for voiding the document', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='voided_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the document was voided', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('cancel', 'Cancel'), ('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('void', 'Void')], default='pending', max_length=20),
        ),
    ]
