# Generated by Django 4.2.9 on 2025-12-13 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0086_document_void_reason_document_voided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
