# Generated by Django 4.2.9 on 2025-12-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0087_document_voided_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='approver_is_submitter',
            field=models.BooleanField(default=False, help_text='If True, the document submitter will be the approver for this step'),
        ),
    ]
