# Generated by Django 4.2.9 on 2025-12-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0088_approvalstep_approver_is_submitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='internal_comment',
            field=models.TextField(blank=True, help_text='Comment visible only to other approvers'),
        ),
    ]
