# Generated by Django 4.2.9 on 2025-12-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('document', '0089_approval_internal_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalworkflow',
            name='denied_groups',
            field=models.ManyToManyField(blank=True, help_text='Users in these groups cannot see or submit to this workflow (Deny List).', related_name='denied_workflows', to='auth.group'),
        ),
    ]
