# Generated by Django 4.2.9 on 2026-01-26 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0090_approvalworkflow_denied_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='condition_logic',
            field=models.CharField(choices=[('and', 'AND (All conditions must be met)'), ('or', 'OR (Any condition can be met)')], default='and', max_length=3),
        ),
        migrations.AlterField(
            model_name='approvalworkflow',
            name='cc_emails',
            field=models.TextField(blank=True, help_text='Comma-separated email addresses for CC (Only sent when document is fully approved)'),
        ),
        migrations.CreateModel(
            name='StepCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('eq', 'Equals'), ('ne', 'Not Equals'), ('gt', 'Greater Than'), ('lt', 'Less Than'), ('gte', 'Greater Than or Equal'), ('lte', 'Less Than or Equal')], max_length=10)),
                ('value', models.CharField(max_length=255)),
                ('condition_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.dynamicfield')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='document.approvalstep')),
            ],
        ),
    ]
